### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by gyscos**
* Run rustfmt
* Update the doc comments to have a short summary on the first line, then a blank line, then the rest of the explanations.
* Minor updates to the constructors and mouse event position

### CODE REVIEW

**Comment by gyscos** [comment]
As a note, `HexView::new_from_iter` looks like it might allocate a new array (I don't know if the compiler can always optimize the iteration & map away - looking at the ASM from [this example](https://play.rust-lang.org/?gist=d961637869f5cee2a4e7ed9aeaa3cd88&version=stable) doesn't look conclusive...), which may become problematic if you want to load large files.

**Comment by hellow554** [comment]
Looks very good, thank you.
Just one thing is, that I don't like 80 characters per line, instead I go typically for 120. Can you please redo the rustfmt part with 120 chars? (max_width = 120 in your .rustfmt.toml)

Maybe I should put a rustfmt in the root dir to make it easier for future uses, hmm.

**Comment by gyscos** [comment]
Added  a rustfmt.toml

**Comment by hellow554** [comment]
Thank you

**Pull request merged**
